export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_PENDING = 'LOGIN_PENDING';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_NETWORK_SUCCESS = 'ADD_NETWORK_SUCCESS';
export const ADD_NETWORK_FAILURE = 'ADD_NETWORK_FAILURE';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const GET_USER_PENDING = 'GET_USER_PENDING';

export const GET_USER_ATTENDANCE_SUCCESS = 'GET_USER_ATTENDANCE_SUCCESS';
export const GET_USER_ATTENDANCE_FAILURE = 'GET_USER_ATTENDANCE_FAILURE';
export const GET_USER_ATTENDANCE_PENDING = 'GET_USER_ATTENDANCE_PENDING';

export const GET_USER_ATTENDANCE_BY_DATE_SUCCESS = 'GET_USER_ATTENDANCE_BY_DATE_SUCCESS';
export const GET_USER_ATTENDANCE_BY_DATE_FAILURE = 'GET_USER_ATTENDANCE_BY_DATE_FAILURE';
export const GET_USER_ATTENDANCE_BY_DATE_PENDING = 'GET_USER_ATTENDANCE_BY_DATE_PENDING';

export const GET_USER_ATTENDANCE_BY_DATE_AND_ID_SUCCESS = 'GET_USER_ATTENDANCE_BY_DATE_AND_ID_SUCCESS';
export const GET_USER_ATTENDANCE_BY_DATE_AND_ID_FAILURE = 'GET_USER_ATTENDANCE_BY_DATE_AND_ID_FAILURE';
export const GET_USER_ATTENDANCE_BY_DATE_AND_ID_PENDING = 'GET_USER_ATTENDANCE_BY_DATE_AND_ID_PENDING';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USERS_PENDING = 'GET_USERS_PENDING';

